# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 6d1610c209da07f54ff807d564fd468da709af839b2381c1561d65a153851f081a66e9b326f5efe21501a1ed0cddd947c91e2dd1ec78d298eafdd2dca748c722

test:
  domain_name: example.com
  secret_key_base: 38b10537559c9348092d2e87063558c4a03647858835c8a45fe20ac2527706cad8af8d34ad62be4c29627cd6ad2fcb723e2c3498b59f47dd7ef0b9a635929955

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: user@example.com
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 38b10537559c9348092d2e87063558c4a03647858835c8a45fe20ac2527706cad8af8d34ad62be4c29627cd6ad2fcb723e2c3498b59f47dd7ef0b9a635929955
